Resources:
  ec2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: "NetworkOps"
      ImageId: "ami-019527627334a2xxx"
      InstanceType: "t2.micro"
      SecurityGroupIds:
        - "sg-0822d6068a51e7xxx"
      SubnetId: "subnet-091ea0afeafb99xxx"


      Tags:
        - Key: "map-migrated"
          Value: "d-server-02eyhorw18lxxx"
        - Key: "CNAME"
          Value: "phx-devl04661.cloud.xxx.com""
        - Key: "BackupGroup"
          Value: "nonprod"
        - Key: "owner"
          Value: "Middleware_Team@xxxx.com"
        - Key: "applicationName"
          Value: "Middleware Portal"
        - Key: "applicationGroup"
          Value: "Middleware Portal"
        - Key: "costCenter"
          Value: "504"
        - Key: "Name"
          Value: "phx-devl04660.xxxx.com"
        - Key: "EOS:AssetID"
          Value: "55580"
        - Key: "os"
          Value: "rhel8"

  ec2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: "NetworkOps"
      ImageId: "ami-019527627334a2xxx"
      InstanceType: "t2.micro"
      SecurityGroupIds:
        - "sg-0822d6068a51e7xxx"
      SubnetId: "subnet-091ea0afeafb99xxx"


      Tags:
        - Key: "map-migrated"
          Value: "d-server-02eyhorw18lwls"
        - Key: "CNAME"
          Value: "middlewareportal.dev.cloud.xxxx.com"
        - Key: "BackupGroup"
          Value: "nonprod"
        - Key: "owner"
          Value: "Middleware_Team@xxxx.com"
        - Key: "applicationName"
          Value: "Middleware Portal"
        - Key: "applicationGroup"
          Value: "Middleware Portal"
        - Key: "costCenter"
          Value: "504"
        - Key: "Name"
          Value: "phx-devl04661.xxxx.com"
        - Key: "EOS:AssetID"
          Value: "55580"
        - Key: "os"
          Value: "rhel8"
  
  loadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: "devmiddlewareportal"
      Scheme: "internal"
      Type: "application"
      SecurityGroups:
        - "sg-0822d6068a51e7xxx"
      Subnets:
        - "subnet-091ea0afeafb99xxx"
        - "subnet-0e5c896143f1ccxxx"
        - "subnet-05f71b3c9efcdaxxx"
      Tags:
        - Key: "applicationGroup"
          Value: "Infrastructure"
        - Key: "applicationName"
          Value: "Middleware Portal"
        - Key: "CNAME"
          Value: "middlewareportal.dev.cloud.xxxx.com"
        - Key: "costCenter"
          Value: "504"
        - Key: "environment"
          Value: "Dev"
        - Key: "EOS:AssetID"
          Value: "55580"
        - Key: "map-migrated"
          Value: "d-server-02eyhorw18lxxx"
        - Key: "Name"
          Value: "Middleware Portal"
        - Key: "os"
          Value: "RedHat 7.6"
        - Key: "owner"
          Value: "Middleware_Team@xxxx.com"
  
  targetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: "devmiddlewareportal"
      Port: 8080
      Protocol: "HTTP"
      Targets:
        - Id: !Ref ec2Instance1
          Port: 8080
        - Id: !Ref ec2Instance2
          Port: 8080
      TargetType: "instance"
      VpcId: "vpc-01d77bcdeb0310xxx"
  
  listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: "forward"
          TargetGroupArn: !Ref targetGroup
      LoadBalancerArn: !Ref loadBalancer
      Port: 80
      Protocol: "HTTP"